/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tzutalin_dlib_PeopleDet */

#ifndef _Included_com_tzutalin_dlib_PeopleDet
#define _Included_com_tzutalin_dlib_PeopleDet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniNativeClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tzutalin_dlib_PeopleDet_jniNativeClassInit
  (JNIEnv *, jclass);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniInit
  (JNIEnv *, jobject);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniDeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniDeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniOpencvHOGDetect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniOpencvHOGDetect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniGetOpecvHOGRet
 * Signature: (Lcom/tzutalin/dlib/VisionDetRet;I)I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniGetOpecvHOGRet
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniDLibHOGDetect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniDLibHOGDetect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniGetDLibHOGRet
 * Signature: (Lcom/tzutalin/dlib/VisionDetRet;I)I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniGetDLibHOGRet
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniDLibHOGFaceDetect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniDLibHOGFaceDetect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniGetDLibHOGFaceRet
 * Signature: (Lcom/tzutalin/dlib/VisionDetRet;I)I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniGetDLibHOGFaceRet
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_tzutalin_dlib_PeopleDet
 * Method:    jniBitmapFaceDect
 * Signature: ([IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tzutalin_dlib_PeopleDet_jniBitmapFaceDect
  (JNIEnv *, jobject, jintArray, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
